export const dictTypes = [
  'ENABLE_STATUS',
  'YES_NO',
  'EXPORT_RECORD_STATUS',
  'OPERATION_AUDIT_ACTION',
  'OPERATION_AUDIT_STATUS',
  'WORK_CALENDAR_CLASSIFICATION_BASIS',
  'WORK_CALENDAR_DATE_OVERRIDE_TYPE',
  'WORK_CALENDAR_DAY_TRAIT',
  'WORK_CALENDAR_EFFECTIVE_DAY_KIND',
  'WORK_CALENDAR_HOLIDAY_STATUS',
  'WORK_CALENDAR_PUBLICATION_CHANGE_TYPE',
  'WORK_CALENDAR_TIME_CLASSIFICATION',
  'WORK_CALENDAR_VERSION_STATUS',
  'WORK_CALENDAR_YEAR_VIEW'
] as const;

export type DictTypes = string;
