export const dictTypes = [
  'ENABLE_STATUS',
  'YES_NO',
  'IAM_STATUS',
  'IAM_DATA_SCOPE_TYPE',
  'IAM_MENU_TYPE',
  'IAM_OPERATION_LOG_ACTION',
  'IAM_OPERATION_LOG_MODULE',
  'IAM_LOGIN_EVENT_TYPE',
  'IAM_LOGIN_RESULT',
  'IAM_LOGIN_FAILURE_REASON',
  'EXPORT_RECORD_STATUS',
  'OPERATION_AUDIT_ACTION',
  'OPERATION_AUDIT_STATUS',
  'WORK_CALENDAR_CLASSIFICATION_BASIS',
  'WORK_CALENDAR_DATE_OVERRIDE_TYPE',
  'WORK_CALENDAR_DAY_TRAIT',
  'WORK_CALENDAR_EFFECTIVE_DAY_KIND',
  'WORK_CALENDAR_HOLIDAY_STATUS',
  'WORK_CALENDAR_PUBLICATION_CHANGE_TYPE',
  'WORK_CALENDAR_TIME_CLASSIFICATION',
  'WORK_CALENDAR_VERSION_STATUS',
  'WORK_CALENDAR_YEAR_VIEW'
] as const;

export type DictTypes = (typeof dictTypes)[number];
